#!/bin/bash

echo "=== GitHub推送助手 ==="
echo "请按照以下步骤手动推送代码到GitHub："
echo ""
echo "1. 首先确保您已经登录GitHub"
echo ""
echo "2. 如果使用HTTPS（推荐）："
echo "   git remote set-url origin https://github.com/qinshu1109/sjgl.git"
echo "   git push -u origin main"
echo "   (系统会提示输入GitHub用户名和密码/token)"
echo ""
echo "3. 如果使用SSH："
echo "   首先配置SSH密钥："
echo "   ssh-keygen -t rsa -b 4096 -C \"your_email@example.com\""
echo "   cat ~/.ssh/id_rsa.pub"
echo "   (将公钥添加到GitHub Settings -> SSH and GPG keys)"
echo ""
echo "   然后推送："
echo "   git remote set-url origin git@github.com:qinshu1109/sjgl.git"
echo "   git push -u origin main"
echo ""
echo "4. 或者使用GitHub CLI (gh):"
echo "   gh auth login"
echo "   git push -u origin main"
echo ""
echo "当前Git状态："
git status --short
echo ""
echo "当前远程仓库："
git remote -v